# Generated by Django 4.0.6 on 2022-07-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicles_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('speed', models.FloatField()),
            ],
        ),
    ]
