# Generated by Django 4.0.6 on 2022-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='direction',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
    ]
